nginx/ngx-rust

- Cargo.lock
- Cargo.toml
- README.md
- examples/README.md
- nginx-sys/Cargo.toml
- nginx-sys/src/lib.rs
- src/core/buffer.rs
- src/core/mod.rs
- src/core/pool.rs
- src/http/request.rs
- src/http/status.rs
- src/lib.rs
Prepare crates to be published to crates.io:
- updated Cargo.toml and added missing fields that are required for publishing to crates.io
- updated documentation 
- updated bindgen to "0.65.0"
- added repostatus and crates badges
- 
> publish to crates.io

- .cargo/config.toml
This workaround is required for both Intel and Apple silicon Macs. 
I do not think there is a way to target both triples without duplication.
> cargo: make macOS linker flags workaround apply to Apple silicon

- nginx-sys/src/lib.rs
- src/core/status.rs
- src/http/module.rs
- src/http/request.rs
- src/http/status.rs
- src/lib.rs
- tests/log_test.rs
All clippy errors and warnings save for #38 
- [X ] I have written my commit messages in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format. 
- [X ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [X ] I have added tests (when possible) that prove my fix is effective or that my feature works
- [X ] I have checked that all unit tests pass after adding my changes
- [X ] I have updated necessary documentation
- [X ] I have rebased my branch onto master
- [X ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork
> chore: clippy lint -Dwarnings

- Cargo.lock
- Cargo.toml
- nginx-sys/Cargo.toml
- nginx-sys/src/lib.rs
- src/http/request.rs
this PR complements changes from https://github.com/nginxinc/ngx-rust/pull/38. 
> Issue 32 lint unsafe

- src/http/conf.rs
- src/http/mod.rs
- src/http/request.rs
- src/http/upstream.rs
- functions to get mut and const module context from the ngx_http_upstream_srv_conf_t
- Request from trait
- Request upstream getter
- Request peer init macro
Previous logging changes are moved to #40 
Fixes #30  (replaces PR #35 )
- [X ] I have written my commit messages in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format. 
- [X ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [X ] I have added tests (when possible) that prove my fix is effective or that my feature works
- [X ] I have checked that all unit tests pass after adding my changes
- [X ] I have updated necessary documentation
- [X ] I have rebased my branch onto master
- [X ] I will ensure my PR is targeting the …
> feat: (1 of 2) Supporting changes for upstream example module.

- examples/Cargo.toml
- examples/README.md
- examples/upstream.conf
- examples/upstream.rs
Upstream example
- derived from github.com/gabihodoroaga/nginx-upstream-module and NGINX ngx_http_upstream_keepalive_module.c
Simply replaces peer functions with passthrough versions, i.e., proxies
traffic through this module to originally configured upstream functions.
Useful as a guide and example, but does not add load balancing
algorithms.
Fixes #30 (replaces PR #35)
- [X ] I have written my commit messages in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format. 
- [X ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [X ] I have added tests (when possible) that prove my fix is effective or that my feature works
- [X ] I have checked that all unit tests pass after adding my …
> feat: (2 of 2) Upstream module example

- src/http/request.rs
When a client sends a request without a `user-agent` header (curl -H "user-agent:") then `pub fn user_agent(&self)` would crash.
> fix: check user_agent for null

- .github/workflows/ci.yaml
- src/core/pool.rs
- src/http/request.rs
- src/log.rs
Run Clippy in CI and fix existing Clippy warnings. 
> ci: run clippy in CI 

- README.md
- examples/curl.rs
- nginx-sys/build.rs
This PR include a fix for the issues below: 
- https://github.com/nginxinc/ngx-rust/issues/41
- https://github.com/nginxinc/ngx-rust/issues/50
> Fix for #41 and #50

- .github/workflows/ci.yaml
- Dockerfile
- examples/upstream.rs
- src/lib.rs
This PR seeks to fix the examples source files that fail to compile on arm64.
> Fix examples that fail to compile

- examples/upstream.rs
- src/lib.rs
This change reverts a previous change that did platform detection and set a type correspondingly to u8 or i8. By using std::ffi::c_char we get a portable way to do the same thing.
This PR fixes a shortcoming with the change in commit: d66f3418d64a4acf18d6b9139db89cd0ec775690
> fix: use std::ffi::c_char instead of platform specific int

- README.md
- nginx-sys/build.rs
This is a copy of the changes submitted as part of the PR: https://github.com/nginxinc/ngx-rust/pull/69
I've bundled a single clippy fix with these changes.
> feat: build script support earlier Nginx version

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- README.md
- nginx-sys/build.rs
- tests/build.rs
- tests/log_test.rs
This PR add some environment variable options useful to develop modules using the SDK.
Default: `[nginx-sys's root]/.cache`
Specify cache directory. With relative -> absolute path converting option provided in `.cargo/config.toml` like below, we are able to generate a project-owned cache dir:
```toml
[env]
CACHE_DIR = { value = ".cache", relative = true }
```
This option makes it easier to save and restore the cache, which speeds up CI/CD.
Originally the default location of the cache dir is in the parent dir of the manifest dir (= root dir) of `nginx-sys`: this is equivalent to set the default of `CACHE_DIR` as `[nginx-sys's root]/../.cache`. This setting resulted the cache dir to be generated in the root dir of `ngx-rust` as long as `ngx-rust` is treated as the main project (this is …
> feat: modify cache & NGINX dir

- examples/async.rs
- examples/awssig.rs
- examples/curl.rs
- examples/upstream.rs
This PR removes shared references to mutable statics, which is announced to be treated as hard error in 2024 edition.
Link to the issue: https://github.com/rust-lang/rust/issues/114447
While the compiler suggests to use `addr_of!()` or `addr_of_mut!()`, In most cases we use `borrow()` because we need not raw pointers but references.
> fix: remove shared ref to static mut

- nginx-sys/build.rs
Roman's key is necessary to build for nginx 1.25.5.
You can verify the key is legitimate through:
```
wget https://nginx.org/download/nginx-1.25.5.tar.gz
wget https://nginx.org/download/nginx-1.25.5.tar.gz.asc
gpg --verify nginx-1.25.5.tar.gz.asc
```
It is also here: https://keyserver.ubuntu.com/pks/lookup?search=43387825DDB1BB97EC36BA5D007C8D7C15D87369&fingerprint=on&op=index
> fix: add required pubkey for 1.25.5

- examples/httporigdst.rs
The example is disabled by default and was missed in #73
> fix: silence remaining shared ref to static mut warning

- Cargo.lock
- examples/Cargo.toml
This gets us to the current stable version of `http`.
Tested manually.
> chore: update aws-sign-v4 and http dependencies

- Dockerfile
- README.md
- src/lib.rs
Sync rustdoc variable defaults with README
Missed that when bumping the default in nginx-sys.
> chore: update remaining instances of NGX_VERSION

- examples/httporigdst.rs
- nginx-sys/src/lib.rs
- src/core/pool.rs
`ngx_str_t` likely does *not* contain UTF-8, so converting it from/to UTF-8 strings is expensive and useless. `from_bytes()` and `as_bytes()` should be a more appropriate interface.
At some point in the future I intend to drop the `String`/`&str` conversion methods, as these aren't safe.
> Byte-oriented methods for `ngx_str_t`

- src/http/request.rs
Fix `get_module_loc_conf` result lifetime that made the Rust compiler think we're borrowing from the `Request`.
Expose `srv_conf` and `main_conf`.
> Fix configuration lifetime and expose more config scopes

- examples/async.rs
- examples/awssig.rs
- examples/curl.rs
- examples/httporigdst.rs
- examples/upstream.rs
- rustfmt.toml
- src/core/buffer.rs
- src/core/mod.rs
- src/core/pool.rs
- src/core/status.rs
- src/core/string.rs
- src/http/conf.rs
- src/http/module.rs
- src/http/request.rs
- src/http/status.rs
- src/http/upstream.rs
- src/lib.rs
- tests/log_test.rs
Non-functional change: reshuffle imports and ensure that the crate types don't leak from the exported macros.
> chore: group and reorder import statements

- .github/workflows/ci.yaml
- .github/workflows/nginx.yaml
- Cargo.toml
- examples/Cargo.toml
- examples/awssig.rs
- examples/config
- examples/httporigdst.rs
- examples/t/awssig.t
- examples/t/curl.t
- examples/t/upstream.t
- nginx-sys/src/lib.rs
- src/core/buffer.rs
- src/core/pool.rs
- src/http/module.rs
- src/http/request.rs
- src/log.rs
* Test the whole process of building Rust code with `--add-dynamic-module` and the resulting modules with our Perl test framework
* Fix doctests for nginx-sys and add to CI
* Fix rustdoc warnings and add to CI
* Fix all remaining clippy warnings
> test: integration tests for example modules

- .github/workflows/ci.yaml
- Cargo.toml
- examples/Cargo.toml
- nginx-sys/Cargo.toml
- rustfmt.toml
> feat!: set supported Rust version to 1.79.0

- .cargo/config.toml
- Cargo.lock
- build.rs
- examples/Cargo.toml
- nginx-sys/Cargo.toml
- nginx-sys/README.md
- nginx-sys/build/main.rs
- nginx-sys/src/lib.rs
- tests/conditional-compilation.rs
Nginx has various configuration options that may affect the availability of functions, constants and structure fields. This is not something that can be detected at runtime, as an attempt to use a symbol unavailable in the bindings would result in compilation error.
This PR introduces translation of a limited subset of `NGX_...` macros to the Rust `cfg` flags,  allowing conditional checks like `#[cfg(ngx_feature = "debug")]`.
There's no publicly available code that uses these flags _yet_, but I already need the functionality for some WIP stuff.
> feat: conditional compilation support

- nginx-sys/build/vendored.rs
- src/http/request.rs
- `clippy::needless_lifetimes` in request.rs
- `clippy::unnecessary-map-or` in vendored.rs
> chore: fix new clippy warnings

- examples/async.rs
- examples/awssig.rs
- examples/curl.rs
- examples/httporigdst.rs
- examples/upstream.rs
- src/http/request.rs
- src/http/upstream.rs
- src/lib.rs
`#[no_mangle]` is only necessary for the symbols that are exported by **name**. That is, exported module lists for the `cdylib` build and individual `ngx_module_t` globals for the `staticlib`.
`extern "C"` ABI specification is sufficient for all the remaining symbols that we pass to the NGINX C code by address.
Fixes: https://github.com/nginxinc/ngx-rust/issues/102
> fix: remove unnecessary `#[no_mangle]` attributes

- Cargo.toml
- examples/Cargo.toml
- nginx-sys/build/main.rs
- nginx-sys/src/lib.rs
- src/core/buffer.rs
- src/core/mod.rs
- src/core/pool.rs
- src/core/status.rs
- src/core/string.rs
- src/http/conf.rs
- src/http/module.rs
- src/http/request.rs
- src/http/status.rs
- src/lib.rs
add features `std`, `alloc` to prepare for `no_std` build support.
- `alloc` feature means memory allocation used. Implementation differs depending on `std` feature:
- with `std`: use `std` crate components. (e.g. `std::string::String`)
- without `std`: use `alloc` crate components. (e.g. `alloc::string::String`)
- `std` feature means `std` crate components used. Currently the only difference between `std` and `alloc` is impl of `std::error::Error` (`core::error::Error` is not in Rust 1.79.0), which is not used.
`alloc` is the transitional feature: while it enables `no_std` build, it allows memory allocation using `std::alloc::System` internally. We can gradually replace `alloc` crate components by nginx-based ones.
For these features, many `std` imports are replaced by `core` ones. …
> add `std`,`alloc` feature flag to support `no_std` build

- examples/upstream.rs
- src/lib.rs
- src/log.rs
Less ambitious attempt to rewrite the logger.
Two goals for this PR:
- add `ngx_log_error!`/`ngx_log_conf_error` macros
- avoid allocations in the logger
> Logging improvements, second try

- Cargo.lock
- deny.toml
- nginx-sys/Cargo.toml
- nginx-sys/build/main.rs
db065fa does not build with 1.79.0, but reordering the commits only makes things worse because `bindgen::RustTarget::from_str` in 0.70.x is unable to parse the full Rust version string.
In case if you are wondering why we are not using dependabot, here's the update task status:
<details>
<https://github.com/nginxinc/ngx-rust/network/updates/943285251>
```
Update check skipped
Dependabot updates have stopped for your repository due to repeated errors. To see logs, click "Check for Updates" and Dependabot will try again. The last error message was:
Dependabot can't resolve your Rust dependency files
Dependabot failed to update your dependencies because there was an error resolving your Rust dependency files.
Dependabot encountered the following error:
error: failed to load manifest for …
```
> chore: update dependencies

- Cargo.toml
- GNUmakefile
- README.md
- examples/README.md
- examples/async.rs
- src/lib.rs
Updating all references to 'nginxinc' as a part of a move to the [nginx](https://github.com/nginx) GitHub organization.
GitHub leaves a redirect in place of a transferred repository, so all the external links to the nginxinc/ngx-rust will remain valid.
<https://crates.io/crates/ngx> will need a new release to pick up the changes.
> chore: update repository links to `nginx/ngx-rust`

- .github/dependabot.yml
- examples/Cargo.toml
- Check github-actions updates.
- Configure dependabot to send a weekly batch of updates.
- Restrict to a semver-compatible changes in the lockfile.
- Work around the issue with the `examples` package.
> chore: update dependabot configuration

- nginx-sys/build/main.rs
- src/log.rs
Fixed the error below, caused by a different signature of `ngx_log_error_core` when neither `NGX_HAVE_C99_VARIADIC_MACROS` nor nor `NGX_HAVE_GCC_VARIADIC_MACROS` is detected.
An example of affected configuration is MinGW with clang or gcc, where we skip most of the compiler feature checks.
```
error[E0061]: this function takes 5 arguments but 6 arguments were
supplied
--> examples\awssig.rs:312:9
|
312   |         ngx_log_debug_http!(request,  "headers {:?}",  headers);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unexpected argument #6 of type `*const u8`
|
note: expected `*mut i8`,  found `usize`
```
> fix(log): support nginx built without variadic macros

- Dockerfile
This PR fixes an inconsistency in the casing of `FROM` and `AS` in the Dockerfile.  
Currently, `FROM` is uppercase while `as` is lowercase, which can trigger warnings in certain build environments.  
To maintain consistency and follow Dockerfile best practices, `AS` is now capitalized.
```
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)
```
There is no functional change in this PR; it is purely a stylistic improvement.
> fix: inconsistent casing of FROM and AS in Dockerfile

- examples/async.rs
- nginx-sys/src/event.rs
- nginx-sys/src/lib.rs
- nginx-sys/src/queue.rs
Almost complete set of the missing methods for `ngx_queue_t` and `ngx_event_t`.
* No logs in the `ngx_event_t` code, because the logging infrastructure is not available from `nginx-sys`. Also, because `ngx_event_ident` is evil.
Note that `ngx_event_ident` still lurks in the event loop C code and _will_ be called on your event when you least expect it. 
* A simple test for the queue methods is implemented in a subset of Rust that I'm going to call "C with traits". It passes through `cargo miri test`, which maybe possibly means that it is a valid Rust code.
In all likeliness, we'll have to continue fencing in all the queue operations with `unsafe` and `addr_of_mut!`.
> feat!: reimplement some C macros and inline functions

- nginx-sys/src/lib.rs
- src/core/buffer.rs
- src/core/pool.rs
- src/http/request.rs
This PR removes `# Safety` sections from the rustdocs of functions which are not `unsafe`. I noticed this when reading one of the docs and scanned through the entire repo's use of `# Safety` docs to collect this set. 
The `Request::get_module_*_conf` functions had `Safety` notes describing their invariants but were not `unsafe`, despite definitely being unsafe, so I changed those function signatures instead of removing the docs.
> Docs: remove Safety notes from functions which are not `unsafe`; mark get_module_*_conf unsafe

- .github/workflows/nginx.yaml
- examples/async.rs
- examples/config
- examples/t/async.t
- src/core/mod.rs
- src/http/request.rs
* Use single tokio runtime instance. Move runtime initialization to the worker process.
* Use `ngx_posted_next_events` to avoid posting events to the tail of currently executed queue.
* Move `event` and `done` to the request context, remove `EventData`.
* Ensure the async task cancellation when the request is aborted.
* Test async example in CI.
[feat!: replace `Request.get_inner` with `AsRef`/`AsMut`](https://github.com/nginx/ngx-rust/commit/013f68c4502ac949f43a745c6f6c859e31aada49) technically does not belong here, but it's too small to deserve a PR on its own.
> fix(examples): assorted fixes in the async example

- examples/async.rs
- examples/awssig.rs
- examples/curl.rs
- examples/httporigdst.rs
- examples/upstream.rs
- src/http/conf.rs
- src/http/module.rs
- src/http/request.rs
Safer interface for module configuration access; this PR resolves #105.
Public objects added for several standard HTTP modules from nginx: core, SSL, upstream, HTTP V2, and HTTP V3. New public traits are defined for each module configuration type (main, server, location) and appropriate access functions. These traits are implemented for HTTP module objects mentioned above. New modules should implement necessary traits to use new configuration interface.
New internal trait `HttpModuleConfExt` is defined to access configuration data in nginx types. It is implemented for `ngx_cycle_t`, `ngx_conf_t`, `ngx_http_core_srv_conf_t`, `ngx_http_request_t`, `ngx_http_upstream_srv_conf_t`, and for Rust shell type `ngx::http::Request`.
Original version was prepared by Aleksei Bavshin
Sample changes …
> Safer interface for module configuration access.

- src/core/string.rs
A valid empty `ngx_str_t` is allowed to have an uninitialized data pointer, so calling `slice::from_raw_parts()` on it is not safe.
Thankfully, we've already solved this in `ngx_str_t::as_bytes()` and can just use the method.
Fixes #150
> fix: empty string handling in NgxStr::from_ngx_str

- .git-blame-ignore-revs
- examples/async.rs
- examples/awssig.rs
- examples/curl.rs
- examples/httporigdst.rs
- examples/upstream.rs
- nginx-sys/build/main.rs
- nginx-sys/build/vendored.rs
- nginx-sys/src/event.rs
- nginx-sys/src/lib.rs
- nginx-sys/src/queue.rs
- rustfmt.toml
- src/core/buffer.rs
- src/core/mod.rs
- src/core/pool.rs
- src/core/string.rs
- src/http/conf.rs
- src/http/module.rs
- src/http/request.rs
- src/http/upstream.rs
- src/log.rs
- tests/build.rs
- tests/log_test.rs
120 is too wide for diffing or editing in terminal.
>  chore: reformat with max-width = 100 

- build.rs
- nginx-sys/build/vendored.rs
- nginx-sys/src/lib.rs
- nginx-sys/src/queue.rs
- unwanted_transmutes on bindgen output
- [clippy::io_other_error](https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error)
- [clippy::ptr_eq](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_eq)
- [clippy::uninlined_format_args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args)
> chore: address compiler warnings on nightly

- .github/workflows/ci.yaml
- examples/async.rs
- examples/awssig.rs
- examples/curl.rs
- examples/upstream.rs
- nginx-sys/build/main.rs
- nginx-sys/build/wrapper.h
- nginx-sys/src/lib.rs
- src/core/status.rs
- src/core/string.rs
- src/http/request.rs
Some commits from my allocators feature branch that are not related to the allocator-api or shared memory and can be reviewed independently.
> Miscellaneous fixes

- nginx-sys/src/lib.rs
Like many of the functions defined in nginx-sys, `ngx_list_init` is defined in nginx as an inline function in a C header, so it isnt captured by bindgen. This definition is equivalent to the one in the C header: https://github.com/nginx/nginx/blob/master/src/core/ngx_list.h#L36-L52
Describe the use case and detail of the change. If this PR addresses an issue 
on GitHub, make sure to include a link to that issue here in this description 
(not in the title of the PR).
> nginx-sys: define ngx_list_init

- Cargo.lock
- Cargo.toml
- src/async_/mod.rs
- src/async_/sleep.rs
- src/async_/spawn.rs
- src/lib.rs
- src/log.rs
This change introduces a general infrastructure for spawing async tasks on NGINX event loop.  The only utility offered for now is a timer support via `ngx::async_::sleep`, with async IO and other scenarios being planned for future.
An incomplete connection IO example is available here: https://github.com/bavshin-f5/ngx-rust/tree/async
> feat: minimal async runtime on top of the NGINX event loop

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/cargo-deny.yaml
- .github/workflows/nginx.yaml
- .github/workflows/sanitizers.yaml
- src/lib.rs
We are planning to rename the default branch from `master` to `main` before the next release, tentatively next week.
This seems to take care of all the _internal_ references to master. Unfortunately, nothing we can do with the external ones; hopefully there's not a lot of those.
> chore: replace references to master branch with main

- .github/workflows/sanitizers.yaml
- examples/auto/rust
This makes it more obvious that the variable is consumed by our script and not by the Rust toolchain itself.
Also, ensure that NGX_RUST_TARGET passed from the caller has priority over the detected value.
> fix(auto): rename RUST_TARGET to NGX_RUST_TARGET

- src/async_/spawn.rs
The way we accessed UnsafeCell in the posted event handler was oddly similar to the bad example in the reference[1].
It's not an exact match since we don't have a _shared_ reference to the cell, but I'd still prefer to use the documented way to access the underlying data.
[1]: https://doc.rust-lang.org/stable/std/cell/struct.UnsafeCell.html#memory-layout
> fix(async): potential UB in the scheduler implementation

- examples/async.rs
- examples/awssig.rs
- examples/curl.rs
- examples/shared_dict.rs
- examples/upstream.rs
- nginx-sys/src/lib.rs
- nginx-sys/src/string.rs
See the individual commits.
Both changes are meant to simplify the configuration parsing.
> feat: provide a few convenience methods for `ngx_str_t` and `ngx_array_t`

- src/collections/mod.rs
- src/collections/queue.rs
- src/collections/rbtree.rs
Also, address feedback for the RbTreeMap implementation from https://github.com/nginx/ngx-rust/pull/164
> feat: implement `ngx_queue_t` wrapper and an owning `Queue` on top of it

- src/log.rs
Debug log code is generated only if nginx is configured with debugging.
> fix: eliminate debug log code generation without debug feature in nginx

- src/core/pool.rs
If resizing is requested for the last allocation in the pool, it may be possible to adjust pool data and avoid any real allocations.
> Add optimized grow()/shrink() functions to Allocator implementation for pool

- Cargo.lock
- nginx-src/Cargo.toml
- nginx-src/src/download.rs
- nginx-sys/Cargo.toml
Should fix the following error:
```
[INFO] [stderr]   --- stderr
[INFO] [stderr] 
[INFO] [stderr]   thread 'main' (15) panicked at build/main.rs:139:67:
[INFO] [stderr]   nginx-src build: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
[INFO] [stderr]   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> Another attempt to fix docs.rs builds

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- nginx-sys/Cargo.toml
- src/allocator.rs
- src/async_/resolver.rs
> release: ngx v0.5.0
